# Generated by Django 5.0 on 2023-12-22 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
