# Generated by Django 5.0 on 2023-12-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='attached_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
