# Generated by Django 5.0 on 2023-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todo_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='attached_file',
            field=models.FileField(default='/uploads/default.txt', upload_to='uploads/'),
        ),
    ]
