# Generated by Django 5.0 on 2023-12-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todo_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
