# Generated by Django 5.0 on 2023-12-23 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_todo_assignee_alter_todo_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignee',
            field=models.ManyToManyField(related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.group'),
        ),
    ]
