# Generated by Django 5.0 on 2023-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_todo_assignee_alter_todo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='attached_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
