# Generated by Django 5.0 on 2023-12-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todo_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
    ]
